name: Deploy to Plesk

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: security-dashboard/package-lock.json
      
      - name: Install Dependencies
        working-directory: ./security-dashboard
        run: |
          npm ci
          npm i -D @types/pocketbase
          npm list pocketbase
          npm list @types/pocketbase
          
      - name: Type Check
        working-directory: ./security-dashboard
        run: |
          echo "Running TypeScript check..."
          npx tsc --noEmit
          
      - name: Build
        working-directory: ./security-dashboard
        if: always()  # Önceki adım başarısız olsa bile build'i dene
        run: |
          echo "Starting build process..."
          npm run build
        env:
          VITE_POCKETBASE_URL: 'https://checklist.rooterbyte.com'
          
      - name: Deploy to Plesk
        if: success()  # Sadece build başarılı olursa deploy et
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: checklist.rooterbyte.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./security-dashboard/dist/
          server-dir: /httpdocs/
          dangerous-clean-slate: true
