name: Deploy to Plesk

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      # Proje dizinine git
      - name: Change to project directory
        run: |
          cd security-dashboard
          pwd  # Debug için dizini yazdır
          ls -la  # Debug için dosyaları listele
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: security-dashboard/package-lock.json
      
      # Bağımlılıkları yükle
      - name: Install Dependencies
        working-directory: ./security-dashboard
        run: npm ci
          
      # Build al
      - name: Build
        working-directory: ./security-dashboard
        run: npm run build
        env:
          VITE_POCKETBASE_URL: 'https://checklist.rooterbyte.com'
          
      # Deploy et
      - name: Deploy to Plesk
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: checklist.rooterbyte.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./security-dashboard/dist/
          server-dir: /httpdocs/
          dangerous-clean-slate: true
